version: '3.12.3'
services:
        web:
                image: healthmedia
                build: .
                env_file:
                        - .env # This file is optional; defaults will be used if it does not exist
                ports:
                        - "8891:8891"
                volumes:
                        - ./instance:/instance
                restart: unless-stopped
